fakeNames = [
    "Zayden Alderwood", "Brayleigh Briarwood", "Jaxxton Cedarbrook", 
    "Kaisleigh Dunmore", "Kyree Elmwood", "Braxtyn Fairchild", 
    "Nayvie Glenhaven", "Zaelie Harperfield", "Brexleigh Ironwood", 
    "Xayvion Juniperhill", "Braxtlee Kingsley", "Kaelin Larkspur", 
    "Maxtyn Meadowbrook", "Kwynn Noblecrest", "Rhylen Oakley", 
    "Jayvion Parkhurst", "Jaxzyn Queensway", "Raelin Riverside", 
    "Kynsley Stonebridge", "Jaxxen Thornbush", "Braxlyn Upland", 
    "Kaeli Valleyview", "Maxxen Whitewood", "Xaela Xavierhill", 
    "Raylen Yellowstone", "Zaxlee Zephyr", "Kairi Ashford", 
    "Braxdyn Bridgewater", "Jaylee Cliffside", "Zaylie Driftwood", 
    "Zion Alderwood", "Bristol Briarwood", "Caden Cedarbrook", 
    "Daphne Dunmore", "Easton Elmwood", "Felicity Fairchild", 
    "Granger Glenhaven", "Hazel Harperfield", "Isadora Ironwood", 
    "Jasper Juniperhill", "Kamryn Kingsley", "Leif Larkspur", 
    "Makenna Meadowbrook", "Nash Noblecrest", "Ophelia Oakley", 
    "Pierce Parkhurst", "Quinn Queensway", "Reagan Riverside", 
    "Sawyer Stonebridge", "Taryn Thornbush", "Uriah Upland", 
    "Vera Valleyview", "Weston Whitewood", "Xander Xavierhill", 
    "Yara Yellowstone", "Zara Zephyr", "Asher Ashford", 
    "Blakely Bridgewater", "Carter Cliffside", "Daxton Driftwood", 
    "Evelyn Alderwood", "Flynn Briarwood", "Gemma Cedarbrook", 
    "Hudson Dunmore", "Isabelle Elmwood", "Jett Fairchild", 
    "Kensington Glenhaven", "Landon Harperfield", "Madison Ironwood", 
    "Niamh Juniperhill", "Odin Kingsley", "Piper Larkspur", 
    "Quincy Meadowbrook", "Raven Noblecrest", "Sage Oakley", 
    "Tegan Parkhurst", "Una Queensway", "Vaughn Riverside", 
    "Wyatt Stonebridge", "Xyla Thornbush", "Yvette Upland", 
    "Zion Valleyview", "Adalyn Whitewood", "Beckett Xavierhill", 
    "Cassidy Yellowstone", "Dante Zephyr", "Ella Ashford", 
    "Finn Bridgewater", "Gabriella Cliffside", "Hunter Driftwood"
]

fakeProjectNames = ["NeuralNetX", "DataVision", "CodeCrushers", "BitBusters", "AIChallengers", "InfiniteLoop", "PixelPioneers", "Streamline", "DataGuardian", "CodeMasters", "PixelPro", "CyberScope", "DataDreamers", "CodeCatalysts", "PixelPerfect", "QuantumLeap", "DataDetectives", "CodeCommanders", "PixelPushers", "MindMeld", "DataDelight", "CodeCreators", "PixelPals", "CyberSavvy", "DataDynamos", "CodeCrusaders", "PixelPlay", "BrainWave", "DataDazzle", "CodeConquerors", "PixelProphet", "CyberSense", "DataDeities", "CodeChampions", "PixelPlunge", "NeuroNexus", "DataDynamo", "CodeClimbers", "PixelPursuit", "MindScope"]

fileMimeTypes = [
    "application/pdf",
    "application/msword",
    "application/vnd.ms-excel",
    "application/vnd.ms-powerpoint",
    "application/zip",
    "application/vnd.android.package-archive",
    "application/x-rar-compressed",
    "application/x-tar",
    "application/gzip",
    "image/jpeg",
    "image/png",
    "image/gif",
    "audio/mpeg",
    "audio/wav",
    "audio/ogg",
    "video/mp4",
    "video/avi",
    "video/mpeg",
    "text/plain",
    "text/html",
    "text/css",
    "text/javascript",
    "application/json",
    "application/xml",
    "application/rss+xml",
    "application/atom+xml"
]